# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
